baseURL = 'https://complexvector.space/'
languageCode = 'en-us'
title = 'ℂ²'
theme = 'hugo-PaperMod'

[params.homeInfoParams]
Title = "Hi there"
Content = "Welcome to my personal website. I might post here from time to time"

[[params.socialIcons]]
name = "github"
url = "https://github.com/maxi0604"

[[params.socialIcons]]
name = "email"
url = "mailto:public@complexvector.space"

[params]
dateFormat = "2006-01-02"
